version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache5
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db5
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8005:80
    db5:
        container_name: db5
        image: mariadb:10.4
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9905:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
             - '8085:80'
        restart: always
        environment:
            PMA_HOST: db5
            UPLOAD_LIMIT: 300M
        depends_on:
                  - db5                